### ISSUE TITLE
announcements_feed module does not exist

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#7262]
# Problem
Acquia reported that sites are throwing errors related to the announcements_feed module.

```
Fatal error: Uncaught Drupal\Core\Extension\Exception\UnknownExtensionException: The module announcements_feed does not exist. in /var/www/html/docroot/core/lib/Drupal/Core/Extension/ExtensionList.php:522
Stack trace:
#0 /var/www/html/docroot/core/lib/Drupal/Core/Extension/ExtensionList.php(541): Drupal\Core\Extension\ExtensionList->getPathname()
#1 /var/www/html/docroot/modules/contrib/acquia_connector/src/EventSubscriber/KernelTerminate/AcquiaTelemetry.php(199): Drupal\Core\Extension\ExtensionList->getPath()
#2 /var/www/html/docroot/modules/contrib/acquia_connector/src/EventSubscriber/KernelTerminate/AcquiaTelemetry.php(240): Drupal\acquia_connector\EventSubscriber\KernelTerminate\AcquiaTelemetry->getExtensionInfo()
#3 /var/www/html/docroot/modules/contrib/acquia_connector/src/EventSubscriber/KernelTerminate/AcquiaTelemetry.php(169): Drupal\acquia_connector\EventSubscriber\KernelTerminate\AcquiaTelemetry->createEvent()
#4 /var/www/html/docroot/modules/contrib/acquia_connector/src/EventSubscriber/KernelTerminate/AcquiaTelemetry.php(110): Drupal\acquia_connector\EventSubscriber\KernelTerminate\AcquiaTelemetry->sendTelemetry()
#5 [internal function]: Drupal\acquia_connector\EventSubscriber\KernelTerminate\AcquiaTelemetry->onTerminateResponse()
#6 /var/www/html/docroot/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(111): call_user_func()
#7 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(115): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch()
#8 /var/www/html/docroot/core/lib/Drupal/Core/StackMiddleware/StackedHttpKernel.php(63): Symfony\Component\HttpKernel\HttpKernel->terminate()
#9 /var/www/html/docroot/core/lib/Drupal/Core/DrupalKernel.php(688): Drupal\Core\StackMiddleware\StackedHttpKernel->terminate()
#10 /var/www/html/vendor/drush/drush/src/Boot/DrupalBoot8.php(394): Drupal\Core\DrupalKernel->terminate()
#11 [internal function]: Drush\Boot\DrupalBoot8->terminate()
#12 {main}
  thrown in /var/www/html/docroot/core/lib/Drupal/Core/Extension/ExtensionList.php on line 522
ERROR: Process exited with status 255
```

# Proposed solution
?

**Comment by joewhitsitt** [comment]
kept running into this running drush on the remotes.

**Comment by joewhitsitt** [comment]
this is still showing up in splunk.

`drush cdel core.extension module.announcements_feed` might be a possible `ume` operation.

**Comment by pyrello** [comment]
> this is still showing up in splunk.
> 
> `drush cdel core.extension module.announcements_feed` might be a possible `ume` operation.

This is a weird issue which I would have expected to sort itself out over a long enough time horizon. The `announcements_feed` module is a newer module that was introduced in one of core updates we did over the last year. However, its not turned on in our stack (and probably never will be unless we repurpose it to show our own announcements feed instead of announcements from drupal.org) so it is confusing why any site would be trying to load it in the first place.

**Comment by joewhitsitt** [comment]
This just started to show up repeated for csv_serialization on https://physicsemfisis.prod.drupal.uiowa.edu/. Yesterday we merged/deployed views_data_export for inrc.law only, which has a dependency requirement for csv_serialization.

I am thinking of trying this on that site followed by a cim/cr. If it is successful, maybe we can finally resolve this for announcements_feed where it is still a problem. (Still showing in splunk)

Reference: https://www.drupal.org/forum/support/post-installation/2019-05-16/the-module-does-not-exist

**Comment by joewhitsitt** [comment]
`Configuration key module.csv_serialization not found.`

**Comment by joewhitsitt** [comment]
pulled the site locally and the module doesn't exist in `key_value` table but does exist, along with `announcements_feed` in the `cache_default` table as part of core.extension.list.module. I think it can be cleared using `drush cc` > `bin` > `default`

TIL `drush cc bin default` also works

**Comment by joewhitsitt** [comment]
Following up.

It seemed that the two sites that continued to choke on the `csv_serialization` issue were fixed by, deleting an orphan database and touching (logging in and moving around) the uiowa default site (it was skipped in deployment which is why we prioritized https://github.com/uiowa/uiowa/pull/8068)

For announcement_feed, it seems to be a periodic issue for uiowa01 default as well as sites that are provisioned but aren't installed at the time? I've ssh'd in to uiowa01.prod and run `drush cr` within the default sites directory to see if that keeps it from acting up again. ¯\_(ツ)_/¯

**Comment by joewhitsitt** [comment]
as of today, warnings are still showing up periodically in Splunk.
